<?php

$moduleFilePath = dirname(__FILE__);
include_once($moduleFilePath . '/classes/class_DbConnect.php');

/**
 * Implementation of hook_perm().
 */
function AppIphone_perm() {
  return array('administer easyapns');
}

/**
 * Implementation of hook_help().
 */
function AppIphone_help($path, $arg) {
  if ($path == 'admin/help#easyapns') {
    $output = '<p>' . t('<b>Send Notification</b> The EasyAPNS module allows users to send notifications on iphone.') . '</p>';
    return $output;
  }
}

/**
 * Implementation of hook_menu().
 */
function AppIphone_menu() {
  $items = array();
  // added to call from url : created in order to test notification from admin panel
  $items['registerDevice'] = array(
    'title' => 'Details',
    'description' => 'User profile details',
    'access arguments' => array('access content'),
    'page callback' => 'appiphone_get',
  );
  $items['appsn/guitin'] = array(
    'title' => 'Details',
    'description' => 'User profile details',
    'access arguments' => array('access content'),
    'file' => 'test/sample_push.php',
    'page callback' => 'apns_sent_ms',
  );
  return $items;
}

function appiphone_get() {
  $token = $_GET['deviceToken'];
  $row['devicetoken'] = $token;
  $row['created'] = time();
  $m= time();
  db_query("INSERT INTO {apns_devices} (devicetoken,created) VALUES ('%s','%s')",$token,$m);
  //drupal_write_record("apns_devices",$row);

}
