<?php

include_once('doji_gold_price.features.inc');

function _doji_gold_price_values($node = NULL) {
  $values = array();
  //HN
  $values['hn_le_muavao'] = 0;
  $values['hn_le_banra'] = 0;
  $values['hn_buon_muavao'] = 0;
  $values['hn_buon_banra'] = 0;
  //HCM
  $values['hcm_le_muavao'] = 0;
  $values['hcm_le_banra'] = 0;
  $values['hcm_buon_muavao'] = 0;
  $values['hcm_buon_banra'] = 0;
  //PHI SJC 99.99
  $values['phi_sjc_9999_muavao'] = 0;
  $values['phi_sjc_9999_banra'] = 0;
  //Nguyên liệu (99.9)
  $values['nguyen_lieu_999_muavao'] = 0;
  $values['nguyen_lieu_999_banra'] = 0;
  //Nguyên liệu (99.9)
  $values['nguyen_lieu_99_muavao'] = 0;
  $values['nguyen_lieu_99_banra'] = 0;
  //SJC HN
  if (isset($node->field_sjc_le_muavao[0]['value'])) {
    $values['hn_le_muavao'] = doji_convert_to_number($node->field_sjc_le_muavao[0]['value']);
  }
  if (isset($node->field_sjc_le_banra[0]['value'])) {
    $values['hn_le_banra'] = doji_convert_to_number($node->field_sjc_le_banra[0]['value']);
  }
  if (isset($node->field_sjc_buon_muavao[0]['value'])) {
    $values['hn_buon_muavao'] = doji_convert_to_number($node->field_sjc_buon_muavao[0]['value']);
  }
  if (isset($node->field_sjc_buon_banra[0]['value'])) {
    $values['hn_buon_banra'] = doji_convert_to_number($node->field_sjc_buon_banra[0]['value']);
  }
  //SJC HN
  if (isset($node->field_sjc_sg_le_muavao[0]['value'])) {
    $values['hcm_le_muavao'] = doji_convert_to_number($node->field_sjc_sg_le_muavao[0]['value']);
  }
  if (isset($node->field_sjc_sg_le_banra[0]['value'])) {
    $values['hcm_le_banra'] = doji_convert_to_number($node->field_sjc_sg_le_banra[0]['value']);
  }
  if (isset($node->field_sjc_sg_buon_muavao[0]['value'])) {
    $values['hcm_buon_muavao'] = doji_convert_to_number($node->field_sjc_sg_buon_muavao[0]['value']);
  }
  if (isset($node->field_sjc_sg_buon_banra[0]['value'])) {
    $values['hcm_buon_banra'] = doji_convert_to_number($node->field_sjc_sg_buon_banra[0]['value']);
  }
  //PHI SJC 99.99
  if (isset($node->field_phi_sjc_9999_muavao[0]['value'])) {
    $values['phi_sjc_9999_muavao'] = doji_convert_to_number($node->field_phi_sjc_9999_muavao[0]['value']);
  }
  if (isset($node->field_phi_sjc_9999_banra[0]['value'])) {
    $values['phi_sjc_9999_banra'] = doji_convert_to_number($node->field_phi_sjc_9999_banra[0]['value']);
  }
  //Nguyên liệu (99.9)
  if (isset($node->field_nguyen_lieu_999_muavao[0]['value'])) {
    $values['nguyen_lieu_999_muavao'] = doji_convert_to_number($node->field_nguyen_lieu_999_muavao[0]['value']);
  }
  if (isset($node->field_nguyen_lieu_999_banra[0]['value'])) {
    $values['nguyen_lieu_999_banra'] = doji_convert_to_number($node->field_nguyen_lieu_999_banra[0]['value']);
  }
  //Nguyên liệu (99)
  if (isset($node->field_nguyen_lieu_99_muavao[0]['value'])) {
    $values['nguyen_lieu_99_muavao'] = doji_convert_to_number($node->field_nguyen_lieu_99_muavao[0]['value']);
  }
  if (isset($node->field_nguyen_lieu_99_banra[0]['value'])) {
    $values['nguyen_lieu_99_banra'] = doji_convert_to_number($node->field_nguyen_lieu_99_banra[0]['value']);
  }

  return $values;
}

/**
 * Implements hook_init().
 */
function doji_gold_price_init() {
  drupal_add_css(drupal_get_path('module', 'doji_gold_price') .'/misc/doji_gold_price.css');
  drupal_add_js(drupal_get_path('module', 'doji_gold_price') .'/misc/gold_price.js');
  $global_settings = variable_get('doji_global_settings', array());

  if (!$global_settings['spread']) {
    $global_settings['spread'] = 0;
  }
  if (!$global_settings['banle_spread']) {
    $global_settings['banle_spread'] = 0;
  }
  if (!$global_settings['banbuon_spread']) {
    $global_settings['banbuon_spread'] = 0;
  }
  if (!$global_settings['click_spread']) {
    $global_settings['click_spread'] = 1;
  }

  $global_settings['spread'] = (float)$global_settings['spread'];
  $global_settings['banle_spread'] = (float)$global_settings['banle_spread'];
  $global_settings['banbuon_spread'] = (float)$global_settings['banbuon_spread'];
  $global_settings['click_spread'] = (float)$global_settings['click_spread'];
  drupal_add_js(array('doji_gold_price' => $global_settings), 'setting');

  if (function_exists('format_number_add_js')) {
    format_number_add_js();
  }
}

/**
 * Implements hook_menu().
 */
function doji_gold_price_menu_alter(&$items) {
  if (isset($items['node/add/goldprice'])) {
    $items['doji/cap-nhat-gia-vang'] = $items['node/add/goldprice'];
    $items['doji/cap-nhat-gia-vang']['page callback'] = 'doji_goldprice_add';
    $items['doji/cap-nhat-gia-vang']['title'] = t('Cập nhập giá', array(), 'vi');
    $items['doji/cap-nhat-gia-vang']['type'] = MENU_LOCAL_TASK;
    $items['doji/cap-nhat-gia-vang']['weight'] = 1;
    unset($items['node/add/goldprice']);
  }
  return $items;
}

/**
 * Implements hook_menu().
 */
function doji_gold_price_menu() {
  $items = array();
  $items['cap-nhat-gia-vang'] = array(
    'title' => t('Cập nhập giá', array(), 'vi'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('doji_gold_price_short_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_CALLBACK,
  );
  $items['trang-thai-giao-dich'] = array(
    'title' => t('Trạng thái giao dịch', array(), 'vi'),
    'page callback' => 'doji_gold_trang_thai_giao_dich',
    'page arguments' => array(1, 2),
    'access arguments' => array('access administration pages'),
    'type' => MENU_CALLBACK,
  );
  $items['xac-thuc-gia'] = array(
    'title' => t('Cập nhập giá', array(), 'vi'),
    'page callback' => 'doji_gold_price_verify_page',
    'page arguments' => array(1),
    'access arguments' => array('access administration pages'),
    'type' => MENU_CALLBACK,
  );
  $items['doji/js/them-gia-nhap-tay'] = array(
    'access arguments' => array('access administration pages'),
    'page callback' => 'doji_gold_price_them_gia_nhap_tay',
    'page arguments' => array(3, 4),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function doji_gold_price_verify_page($op) {
  //Get all messages
  drupal_get_messages();

  $node = doji_get_node('last', 'goldprice', 0);

  if ($node->status || !isset($node->nid)) {
    form_set_error('name', t('Giá nhập vào chưa chính xác. Xin vui lòng kiểm tra lại', array(), 'vi'));
    drupal_goto('<front>');
  }

  $gold_prices = _doji_gold_price_values($node);

  //Validate
  $error_count = doji_gold_price_value_validate($gold_prices);

  if (!$error_count) {
    db_query('UPDATE {node} SET status=1 WHERE vid = %d', $node->vid);
    drupal_set_message(t('Giá vàng cập nhật thành công', array(), 'vi'));

    $dojigold_prefix_filename = variable_get('dojigold_prefix_filename', -32767);
    $dojigold_prefix_filename++;
    variable_set('dojigold_prefix_filename', $dojigold_prefix_filename);
  }
 // $redirect = 'window.location = \'' . $redirect_url . '\';';
  $_SESSION['doji_gold_update'] = 1;
  //doji_export_image_create_block();
  drupal_goto('<front>');
//  return $output;
}

function doji_gold_price_them_gia_nhap_tay($name = NULL, $status = 0) {
  if ($name && is_numeric($status)) {
    $options = doji_gold_price_group_options();
    $goldprice_group_settings = variable_get('goldprice_group_settings', array());
    if (!count($goldprice_group_settings)) {
      foreach ($options as $group_name => $label) {
        $goldprice_group_settings[$group_name]['status'] = 1;
      }
    }
    if (isset($goldprice_group_settings[$name])) {
      $goldprice_group_settings[$name]['status'] = intval($status);
    }
    variable_set('goldprice_group_settings', $goldprice_group_settings);
  }
}

/**
 * Implementation of hook_block().
 *
 */
function doji_gold_price_block($op = 'list', $delta = 0, $edit = array()) {
  global $user;
  switch ($op) {
    case 'list':
      $blocks = array();
      $blocks['add_new_field']['info'] = t('Thêm giá mới', array(), 'vi');
      return $blocks;
    case 'view':
      $blocks = array();
      switch ($delta) {
        case 'add_new_field':
          $blocks['subject'] = t('Thêm giá mới', array(), 'vi');
          $blocks['content'] = drupal_get_form('doji_gold_price_add_new_field');
          break;
      }
      return $blocks;
  }
}

/**
 * Implementation of hook_nodeapi().
 *
 */
function doji_gold_price_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  if ($node->type == 'goldprice') {
    if (arg(2) == 'edit') {
    //drupal_set_message(t('Bạn không thể sửa đổi dữ liệu này', array(), 'vi'));
     //drupal_goto('<front>');
    }
    if (in_array($op, array('insert', 'update')) && !$_GET['import_data']) {

      drupal_goto('xac-thuc-gia');
    }
  }
  if ($node->type == 'doji_goldprice_wget') {
    if (in_array(arg(2), array('edit'))) {
      variable_set('dojigold_prefix_filename', -32767);
      drupal_goto('doji/thiet-lap-gia/sap-xep-hien-thi');
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function doji_gold_price_form_alter(&$form, $form_state, $form_id) {
  global $user;
  if ($form_id == 'goldprice_node_form') {
    if (!drupal_is_front_page()) {
      $form['#attributes']['class'] .= ' goldprice_js_disabled ';
    }
    if (!isset($form['#validate'])) {
      $form['#validate'] = array();
    }
    array_unshift($form['#validate'], 'doji_gold_price_node_form_validate');
  }
}

function doji_gold_price_node_form_validate($form, &$form_state) {
  $node = (object)$form_state['values'];
  $gold_prices = _doji_gold_price_values($node);

  //VALIDATE
  $error = doji_gold_price_value_validate($gold_prices);

  if (!$error) {
    $sess_currencyrates = variable_get('sess_currencyrates', array());
    if (isset($sess_currencyrates['currencyrates'])) {
      $currencyrates = $sess_currencyrates['currencyrates'];
    }

    if (isset($currencyrates->XAUUSD)) {
      $field_gold_muavao = doji_convert_to_number($currencyrates->XAUUSD[0]);
      $field_gold_banra = doji_convert_to_number($currencyrates->XAUUSD[1]);
    }

    if ($field_gold_muavao && $field_gold_banra) {
      $form_state['values']['field_gold_muavao'][0]['value'] = $field_gold_muavao;
      $form_state['values']['field_gold_banra'][0]['value'] = $field_gold_banra;
    }
  }
}

/**
 * Alter the default cck fields right before they are cached into the database.
 *
 * @param &$fields
 *   By reference. The fields that have been declared by another feature.
 */
function doji_gold_price_content_default_fields_alter(&$fields) {
  if (isset($fields['goldprice-field_sjc_le_muavao'])) {
    $goldprice_field = $_POST;
    if (isset($goldprice_field['field_name']) && isset($goldprice_field['name'])) {
      $field_name = $goldprice_field['field_name'];
      $name = $goldprice_field['name'];
      $description = $goldprice_field['description'];
      $fields += doji_gold_price_general_field($field_name, $name, $description);
    }
  }
}

function doji_gold_price_general_field($middle_field, $label, $description = '') {
  // Exported field: field_' . $middle_field .'_banra
  $fields['goldprice-field_' . $middle_field . '_banra'] = array(
    'field_name' => 'field_' . $middle_field . '_banra',
    'type_name' => 'goldprice',
    'display_settings' => array(
      'label' => array(
        'format' => 'above',
        'exclude' => 0,
      ),
      'teaser' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '4' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'token' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'text',
    'required' => '0',
    'multiple' => '0',
    'module' => 'text',
    'active' => '1',
    'text_processing' => '0',
    'max_length' => '',
    'allowed_values' => '',
    'allowed_values_php' => '',
    'widget' => array(
      'rows' => 5,
      'size' => '60',
      'default_value' => array(
        '0' => array(
          'value' => '',
          '_error_element' => 'default_value_widget][field_' . $middle_field . '_banra][0][value',
        ),
      ),
      'default_value_php' => NULL,
      'label' => $label,
      'weight' => '11',
      'description' => '',
      'type' => 'text_textfield',
      'module' => 'text',
    ),
  );

  // Exported field: field_' . $middle_field .'_chenhlech
  $fields['goldprice-field_' . $middle_field . '_chenhlech'] = array(
    'field_name' => 'field_' . $middle_field . '_chenhlech',
    'type_name' => 'goldprice',
    'display_settings' => array(
      'label' => array(
        'format' => 'above',
        'exclude' => 0,
      ),
      'teaser' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '4' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'token' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'text',
    'required' => '0',
    'multiple' => '0',
    'module' => 'text',
    'active' => '1',
    'text_processing' => '0',
    'max_length' => '',
    'allowed_values' => '',
    'allowed_values_php' => '',
    'widget' => array(
      'rows' => 5,
      'size' => '60',
      'default_value' => array(
        '0' => array(
          'value' => '',
          '_error_element' => 'default_value_widget][field_' . $middle_field . '_chenhlech][0][value',
        ),
      ),
      'default_value_php' => NULL,
      'label' => $label,
      'weight' => '12',
      'description' => '',
      'type' => 'text_textfield',
      'module' => 'text',
    ),
  );

  // Exported field: field_' . $middle_field .'_muavao
  $fields['goldprice-field_' . $middle_field . '_muavao'] = array(
    'field_name' => 'field_' . $middle_field . '_muavao',
    'type_name' => 'goldprice',
    'display_settings' => array(
      'label' => array(
        'format' => 'above',
        'exclude' => 0,
      ),
      'teaser' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '4' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'token' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'text',
    'required' => '0',
    'multiple' => '0',
    'module' => 'text',
    'active' => '1',
    'text_processing' => '0',
    'max_length' => '',
    'allowed_values' => '',
    'allowed_values_php' => '',
    'widget' => array(
      'rows' => 5,
      'size' => '60',
      'default_value' => array(
        '0' => array(
          'value' => '',
          '_error_element' => 'default_value_widget][field_' . $middle_field . '_muavao][0][value',
        ),
      ),
      'default_value_php' => NULL,
      'label' => $label,
      'weight' => '10',
      'description' => '',
      'type' => 'text_textfield',
      'module' => 'text',
    ),
  );

  return $fields;
}

/**
 * Alter the default fieldgroup groups right before they are cached into the
 * database.
 *
 * @param &$groups
 *   By reference. The fieldgroup groups that have been declared by another
 *   feature.
 */
function doji_gold_price_fieldgroup_default_groups_alter(&$groups) {
  if (isset($groups['goldprice-group_sjc_le'])) {
    $goldprice_groups = fieldgroup_groups('goldprice');
    $weight = 50;
    $obj = db_fetch_object(db_query('SELECT * FROM {content_group} ORDER BY weight DESC LIMIT 1'));

    if (isset($obj->weight)) {
      $weight = $obj->weight + 1;
    }

    $goldprice_field = $_POST;

    if (isset($goldprice_field['field_name']) && isset($goldprice_field['name'])) {
      $field_name = $goldprice_field['field_name'];
      $name = $goldprice_field['name'];
      $description = $goldprice_field['description'];
      $groups += doji_gold_price_general_group($field_name, $name, $weight, $description);
    }
  }
}

function doji_gold_price_general_group($middle_group, $label, $weight, $description = '') {
  // Exported group: group_' . $middle_group .'
  $groups['goldprice-group_' . $middle_group ] = array(
    'group_type' => 'standard',
    'type_name' => 'goldprice',
    'group_name' => 'group_' . $middle_group,
    'label' => $label,
    'settings' => array(
      'form' => array(
        'style' => 'fieldset',
        'description' => $description,
      ),
      'display' => array(
        'description' => $description,
        'teaser' => array(
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        'full' => array(
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        '4' => array(
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        'token' => array(
          'format' => 'fieldset',
          'exclude' => 0,
        ),
        'label' => 'above',
      ),
    ),
    'weight' => $weight,
    'fields' => array(
      '0' => 'field_' . $middle_group .'_muavao',
      '1' => 'field_' . $middle_group .'_banra',
      '2' => 'field_' . $middle_group .'_chenhlech',
    ),
  );
  return $groups;
}

/**
 * Gold price short form
 *
 */
function doji_gold_price_add_new_field() {
  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Nhập tên giá', array(), 'vi'),
    '#size' => 5,
    '#required' => 1,
  );
  $form['description'] = array(
    '#type' => 'textfield',
    '#title' => t('Mô tả', array(), 'vi'),
    '#size' => 5,
    '#required' => 1,
  );
/*
  $form['position'] = array(
    '#type' => 'select',
    '#title' => t('Đứng trước', array(), 'vi'),
    '#options' => doji_gold_price_group_options(),
  );
*/
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Tạo mới', array(), 'vi'),
  );
  return $form;
}

function doji_gold_price_add_new_field_validate($form, &$form_state) {
}

function doji_gold_price_add_new_field_submit($form, &$form_state) {
  module_load_include('inc', 'pathauto');
  $_POST['field_name'] = pathauto_cleanstring(preg_replace('|(.*?)\(.*|i', '\1', $form_state['values']['name']));
  $_POST['field_name'] = preg_replace('|[^0-9a-z\_\-]|i', '', $_POST['field_name']);
  $_POST['field_name'] = str_replace('-', '_', $_POST['field_name']);

  while (1) {
    $_POST['field_name'] = substr($_POST['field_name'], 0, mt_rand(2, 5)) . mt_rand(0, 9);
    $group_name = 'group_' . $_POST['field_name'];
    $obj = db_fetch_object(db_query_range('SELECT * FROM {content_group} WHERE type_name="%s" AND group_name="%s"', 'goldprice', $group_name, 0, 1));
    if (!isset($obj->type_name)) {
      break;
    }
  }

  features_revert(array('doji_gold_price' => array('content', 'fieldgroup')));
}

/**
 * Gold price short form
 *
 */
function doji_gold_price_short_form() {
  $btn_updown = doji_gold_price_btn_updown();
  $btn_updown_disabled = doji_gold_price_btn_updown(array('class' => 'btn-up btn-updown-children disabled'), array('class' => 'btn-down btn-updown-children disabled'));
  $node = doji_get_node('last');

  $form = array();
  $form['#attributes']['class'] = 'form-goldprice-updown';
  $form['sjc_le_muavao'] = array(
    '#type' => 'textfield',
    '#title' => t('SJC lẻ mua vào', array(), 'vi'),
    '#default_value' => isset($node->field_sjc_le_muavao[0]['value']) ? format_number(str_replace(',', '', $node->field_sjc_le_muavao[0]['value'])) : '',
    '#attributes' => array('class' => 'price-bg hn-pushall', 'oldvalue' => isset($node->field_sjc_le_muavao[0]['value']) ? format_number(str_replace(',', '', $node->field_sjc_le_muavao[0]['value'])) : 0),
    '#size' => 5,
    '#suffix' => $btn_updown,
  );
  $form['sjc_le_banra'] = array(
    '#type' => 'textfield',
    '#title' => t('SJC lẻ bán ra', array(), 'vi'),
    '#default_value' => isset($node->field_sjc_le_banra[0]['value']) ? format_number(str_replace(',', '', $node->field_sjc_le_banra[0]['value'])) : '',
    '#attributes' => array('class' => 'price-bg hn', 'oldvalue' => isset($node->field_sjc_le_banra[0]['value']) ? format_number(str_replace(',', '', $node->field_sjc_le_banra[0]['value'])) : 0),
    '#size' => 5,
    '#suffix' => $btn_updown,
  );
  $form['sjc_buon_muavao'] = array(
    '#type' => 'textfield',
    '#title' => t('SJC buôn mua vào', array(), 'vi'),
    '#default_value' => isset($node->field_sjc_buon_muavao[0]['value']) ? format_number(str_replace(',', '', $node->field_sjc_buon_muavao[0]['value'])) : '',
    '#attributes' => array('class' => 'price-bg hn', 'oldvalue' => isset($node->field_sjc_buon_muavao[0]['value']) ? format_number(str_replace(',', '', $node->field_sjc_buon_muavao[0]['value'])) : 0),
    '#size' => 5,
    '#suffix' => $btn_updown,
  );
  $form['sjc_buon_banra'] = array(
    '#type' => 'textfield',
    '#title' => t('SJC buôn mua vào', array(), 'vi'),
    '#default_value' => isset($node->field_sjc_buon_banra[0]['value']) ? format_number(str_replace(',', '', $node->field_sjc_buon_banra[0]['value'])) : '',
    '#attributes' => array('class' => 'price-bg hn', 'oldvalue' => isset($node->field_sjc_buon_banra[0]['value']) ? format_number(str_replace(',', '', $node->field_sjc_buon_banra[0]['value'])) : 0),
    '#size' => 5,
    '#suffix' => $btn_updown,
  );

  //SJC SG
  $form['sjc_sg_le_muavao'] = array(
    '#type' => 'textfield',
    '#title' => t('SJC HCM lẻ mua vào', array(), 'vi'),
    '#default_value' => isset($node->field_sjc_sg_le_muavao[0]['value']) ? format_number(str_replace(',', '', $node->field_sjc_sg_le_muavao[0]['value'])) : 0,
    '#attributes' => array('class' => 'price-bg sg-pushall', 'oldvalue' => isset($node->field_sjc_sg_le_muavao[0]['value']) ? format_number(str_replace(',', '', $node->field_sjc_sg_le_muavao[0]['value'])) : 0),
    '#size' => 5,
    '#suffix' => $btn_updown,
  );
  $form['sjc_sg_le_banra'] = array(
    '#type' => 'textfield',
    '#title' => t('SJC HCM lẻ bán ra', array(), 'vi'),
    '#default_value' => isset($node->field_sjc_sg_le_banra[0]['value']) ? format_number(str_replace(',', '', $node->field_sjc_sg_le_banra[0]['value'])) : 0,
    '#attributes' => array('class' => 'price-bg sg', 'oldvalue' => isset($node->field_sjc_sg_le_banra[0]['value']) ? format_number(str_replace(',', '', $node->field_sjc_sg_le_banra[0]['value'])) : 0),
    '#size' => 5,
    '#suffix' => $btn_updown,
  );
  $form['sjc_sg_buon_muavao'] = array(
    '#type' => 'textfield',
    '#title' => t('SJC HCM buôn mua vào', array(), 'vi'),
    '#default_value' => isset($node->field_sjc_sg_buon_muavao[0]['value']) ? format_number(str_replace(',', '', $node->field_sjc_sg_buon_muavao[0]['value'])) : 0,
    '#attributes' => array('class' => 'price-bg sg', 'oldvalue' => isset($node->field_sjc_sg_buon_muavao[0]['value']) ? format_number(str_replace(',', '', $node->field_sjc_sg_buon_muavao[0]['value'])) : 0),
    '#size' => 5,
    '#suffix' => $btn_updown,
  );
  $form['sjc_sg_buon_banra'] = array(
    '#type' => 'textfield',
    '#title' => t('SJC HCM buôn mua vào', array(), 'vi'),
    '#default_value' => isset($node->field_sjc_sg_buon_banra[0]['value']) ? format_number(str_replace(',', '', $node->field_sjc_sg_buon_banra[0]['value'])) : 0,
    '#attributes' => array('class' => 'price-bg sg', 'oldvalue' => isset($node->field_sjc_sg_buon_banra[0]['value']) ? format_number(str_replace(',', '', $node->field_sjc_sg_buon_banra[0]['value'])) : 0),
    '#size' => 5,
    '#suffix' => $btn_updown,
  );

  //Phi SJC 99.99
  $form['phi_sjc_9999_muavao'] = array(
    '#type' => 'textfield',
    '#title' => t('Phi SJC (99.99)', array(), 'vi'),
    '#default_value' => isset($node->field_phi_sjc_9999_muavao[0]['value']) ? format_number(str_replace(',', '', $node->field_phi_sjc_9999_muavao[0]['value'])) : 0,
    '#attributes' => array('class' => 'price-bg phi-pushall', 'oldvalue' => isset($node->field_phi_sjc_9999_muavao[0]['value']) ? format_number(str_replace(',', '', $node->field_phi_sjc_9999_muavao[0]['value'])) : 0),
    '#size' => 5,
    '#suffix' => $btn_updown,
  );
  $form['phi_sjc_9999_banra'] = array(
    '#type' => 'textfield',
    '#title' => t('Phi SJC (99.99)', array(), 'vi'),
    '#default_value' => isset($node->field_phi_sjc_9999_banra[0]['value']) ? format_number(str_replace(',', '', $node->field_phi_sjc_9999_banra[0]['value'])) : 0,
    '#attributes' => array('class' => 'price-bg phi', 'oldvalue' => isset($node->field_phi_sjc_9999_banra[0]['value']) ? format_number(str_replace(',', '', $node->field_phi_sjc_9999_banra[0]['value'])) : 0),
    '#size' => 5,
    '#suffix' => $btn_updown,
  );

  //Nguyen Lieu 99.9
  $form['nguyen_lieu_999_muavao'] = array(
    '#type' => 'textfield',
    '#title' => t('Nguyên liệu (99.9)', array(), 'vi'),
    '#default_value' => isset($node->field_nguyen_lieu_999_muavao[0]['value']) ? format_number(str_replace(',', '', $node->field_nguyen_lieu_999_muavao[0]['value'])) : 0,
    '#attributes' => array('class' => 'price-bg nl999-pushall', 'oldvalue' => isset($node->field_nguyen_lieu_999_muavao[0]['value']) ? format_number(str_replace(',', '', $node->field_nguyen_lieu_999_muavao[0]['value'])) : 0),
    '#size' => 5,
    '#suffix' => $btn_updown,
  );
  $form['nguyen_lieu_999_banra'] = array(
    '#type' => 'textfield',
    '#title' => t('Nguyên liệu (99.9)', array(), 'vi'),
    '#default_value' => isset($node->field_nguyen_lieu_999_banra[0]['value']) ? format_number(str_replace(',', '', $node->field_nguyen_lieu_999_banra[0]['value'])) : 0,
    '#attributes' => array('class' => 'price-bg nl999', 'oldvalue' => isset($node->field_nguyen_lieu_999_banra[0]['value']) ? format_number(str_replace(',', '', $node->field_nguyen_lieu_999_banra[0]['value'])) : 0),
    '#size' => 5,
    '#suffix' => $btn_updown,
  );

  //Nguyen Lieu 99
  $form['nguyen_lieu_99_muavao'] = array(
    '#type' => 'textfield',
    '#title' => t('Nguyên liệu (99)', array(), 'vi'),
    '#default_value' => isset($node->field_nguyen_lieu_99_muavao[0]['value']) ? format_number(str_replace(',', '', $node->field_nguyen_lieu_99_muavao[0]['value'])) : 0,
    '#attributes' => array('class' => 'price-bg nl99-pushall', 'oldvalue' => isset($node->field_nguyen_lieu_99_muavao[0]['value']) ? format_number(str_replace(',', '', $node->field_nguyen_lieu_99_muavao[0]['value'])) : 0),
    '#size' => 5,
    '#suffix' => $btn_updown,
  );
  $form['nguyen_lieu_99_banra'] = array(
    '#type' => 'textfield',
    '#title' => t('Nguyên liệu (99)', array(), 'vi'),
    '#default_value' => isset($node->field_nguyen_lieu_99_banra[0]['value']) ? format_number(str_replace(',', '', $node->field_nguyen_lieu_99_banra[0]['value'])) : 0,
    '#attributes' => array('class' => 'price-bg nl99', 'oldvalue' => isset($node->field_nguyen_lieu_99_banra[0]['value']) ? format_number(str_replace(',', '', $node->field_nguyen_lieu_99_banra[0]['value'])) : 0),
    '#size' => 5,
    '#suffix' => $btn_updown,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Cập nhật', array(), 'vi'),
  );
  $form['submit1'] = array(
    '#type' => 'submit',
    '#value' => t('Cập nhật', array(), 'vi'),
  );

  $trangthaigiaodich = variable_get('trangthaigiaodich', 1);

  if (drupal_is_front_page()) {
    $post_updated = '<span class="update-time">' . t('Cập nhập lúc: @time', array('@time' => format_date($node->created, 'custom', 'H:i d/m/Y')), 'vi') . '</span>';
    $form['submit']['#suffix'] = '<div id="show-messages">' . $post_updated . '</div>';
  }

  $special = array();
  $special[] = 'phi_sjc_9999_muavao';
  $special[] = 'phi_sjc_9999_banra';
  $special[] = 'nguyen_lieu_999_muavao';
  $special[] = 'nguyen_lieu_999_banra';
  $special[] = 'nguyen_lieu_99_muavao';
  $special[] = 'nguyen_lieu_99_banra';
  $special[] = 'submit1';

  if (!$trangthaigiaodich) {
    foreach ($form as $key=>$element) {
      if (isset($element['#type']) && !in_array($key, $special)) {
        $form[$key]['#attributes']['disabled'] = 'disabled';
      }
    }
  }

  $trangthaigiaodich_extra = variable_get('trangthaigiaodich_extra', 1);

  if (!$trangthaigiaodich_extra) {
    foreach ($form as $key=>$element) {
      if (isset($element['#type']) && in_array($key, $special)) {
        $form[$key]['#attributes']['disabled'] = 'disabled';
      }
    }
  }

  return $form;
}

function doji_gold_price_short_form_validate($form, &$form_state) {
}

function doji_gold_price_short_form_submit($form, &$form_state) {

}

function doji_gold_price_btn_updown($attribute_up = array('class' => 'btn-up btn-updown-children'), $attribute_down = array('class' => 'btn-down btn-updown-children')) {
  return '
    <div class="btn-updown">
      <span ' . drupal_attributes($attribute_up) . '></span><span ' . drupal_attributes($attribute_down) . '></span>
    </div>
  ';
}

function doji_gold_price_group_options() {
  static $options;

  if (!isset($options)) {
    $groups = fieldgroup_groups('goldprice');
    $options = array();

    foreach ($groups as $group_name => $group) {
      $options[$group['group_name']] = $group['label'];
    }
  }
  return $options;
}

/**
 * Implementation of hook_theme().
 */
function doji_gold_price_theme() {
  return array(
    'doji_gold_price_short_form' => array(
      'arguments' => array(
        'form' => array()
      )
    ),
  );
}

function theme_doji_gold_price_short_form($form) {
  global $user;

  unset($form['sjc_le_muavao']['#title']);
  unset($form['sjc_le_banra']['#title']);
  unset($form['sjc_buon_muavao']['#title']);
  unset($form['sjc_buon_banra']['#title']);
  unset($form['sjc_sg_le_muavao']['#title']);
  unset($form['sjc_sg_le_banra']['#title']);
  unset($form['sjc_sg_buon_muavao']['#title']);
  unset($form['sjc_sg_buon_banra']['#title']);
  unset($form['phi_sjc_9999_muavao']['#title']);
  unset($form['phi_sjc_9999_banra']['#title']);
  unset($form['nguyen_lieu_999_muavao']['#title']);
  unset($form['nguyen_lieu_999_banra']['#title']);
  unset($form['nguyen_lieu_99_muavao']['#title']);
  unset($form['nguyen_lieu_99_banra']['#title']);

  $trangthaigiaodich = variable_get('trangthaigiaodich', 1);

  if ($trangthaigiaodich) {
    $trangthaigiaodich_link = l(t('Ngừng giao dịch vàng', array(), 'vi'), 'trang-thai-giao-dich/0', array('attributes' => array('title' => t('Ngừng giao dịch vàng', array(), 'vi'), 'class' => 'btn-ngunggiaodich')));
  }
  else {
    $trangthaigiaodich_link = l(t('Giao dịch vàng', array(), 'vi'), 'trang-thai-giao-dich/1', array('attributes' => array('title' => t('Giao dịch vàng', array(), 'vi'), 'class' => 'btn-giaodich')));
    $trangthaigiaodich_class = 'form-ngunggiaodich';
  }

  $headers = array();
  $headers[] = array('data' => '<div></div>', 'class' => 'first');
  $headers[] = array('data' => '<div>' . t('Mua', array(), 'vi') .'</div>');
  $headers[] = array('data' => '<div>' . t('Bán', array(), 'vi') .'</div>', 'class' => 'last');

  $rows = array();
  //DOJI HN
  $row = array();
  $row[] = array('data' => t('<span class="title clear-block clear size-18 normal">DOJI HN lẻ</span><span class="sub-title clear size-13 normal">(nghìn/chỉ)</span>', array(), 'vi'), 'class' => 'first');
  $row[] = array('data' => '<div class="item-relative">' . drupal_render($form['sjc_le_muavao']) . '</div>', 'class' => 'goldprice-td goldprice-td-0');
  $row[] = array('data' => '<div class="item-relative">' . drupal_render($form['sjc_le_banra']) . '</div>', 'class' => 'goldprice-td goldprice-td-1');
  $rows[] = $row;

  $row = array();
  $row[] = array('data' => t('<span class="title clear-block clear size-18 normal">DOJI HN buôn</span><span class="sub-title clear size-13 normal">(nghìn/chỉ)</span>', array(), 'vi'), 'class' => 'first');
  $row[] = array('data' => '<div class="item-relative">' . drupal_render($form['sjc_buon_muavao']) . '</div>', 'class' => 'goldprice-td goldprice-td-0');
  $row[] = array('data' => '<div class="item-relative">' . drupal_render($form['sjc_buon_banra']) . '</div>', 'class' => 'goldprice-td goldprice-td-1');
  $rows[] = $row;

  //DOJI SG
  $row = array();
  $row[] = array('data' => t('<span class="title clear-block clear size-18 normal">DOJI HCM lẻ</span><span class="sub-title clear size-13 normal">(nghìn/chỉ)</span>', array(), 'vi'), 'class' => 'first');
  $row[] = array('data' => '<div class="item-relative">' . drupal_render($form['sjc_sg_le_muavao']) . '</div>', 'class' => 'goldprice-td goldprice-td-0');
  $row[] = array('data' => '<div class="item-relative">' . drupal_render($form['sjc_sg_le_banra']) . '</div>', 'class' => 'goldprice-td goldprice-td-1');
  $rows[] = $row;

  $row = array();
  $row[] = array('data' => t('<span class="title clear-block clear size-18 normal">DOJI HCM buôn</span><span class="sub-title clear size-13 normal">(nghìn/chỉ)</span>', array(), 'vi'), 'class' => 'first');
  $row[] = array('data' => '<div class="item-relative">' . drupal_render($form['sjc_sg_buon_muavao']) . '</div>', 'class' => 'goldprice-td goldprice-td-0');
  $row[] = array('data' => '<div class="item-relative">' . drupal_render($form['sjc_sg_buon_banra']) . '</div>', 'class' => 'goldprice-td goldprice-td-1');
  $rows[] = $row;

  $submit_btn = drupal_render($form['submit']);
  $submit_button = array('data' => $trangthaigiaodich_link . $submit_btn, 'class' => 'form-footer-container', 'colspan' => 3);
  $output = theme('table', $headers, $rows, array('class' => 'goldprice-view ' . $trangthaigiaodich_class));

  $rows = array();
  $row = array();
  $row[] = $submit_button;
  $rows[] = $row;
  unset($trangthaigiaodich_class);

  $trangthaigiaodich = variable_get('trangthaigiaodich_extra', 1);

  if ($trangthaigiaodich) {
    $trangthaigiaodich_link = l(t('Ngừng giao dịch nguyên liệu', array(), 'vi'), 'trang-thai-giao-dich/extra/0', array('attributes' => array('title' => t('Ngừng giao dịch nguyên liệu', array(), 'vi'), 'class' => 'btn-ngunggiaodich')));
  }
  else {
    $trangthaigiaodich_link = l(t('Giao dịch nguyên liệu', array(), 'vi'), 'trang-thai-giao-dich/extra/1', array('attributes' => array('title' => t('Giao dịch nguyên liệu', array(), 'vi'), 'class' => 'btn-giaodich')));
    $trangthaigiaodich_class = 'form-ngunggiaodich';
  }

  //Phi SJC 9999
  $row = array();
  $row[] = array('data' => t('<span class="title clear-block clear size-18 normal">Phi SJC 99.99</span><span class="sub-title clear size-13 normal">(nghìn/chỉ)</span>', array(), 'vi'), 'class' => 'first');
  $row[] = array('data' => '<div class="item-relative">' . drupal_render($form['phi_sjc_9999_muavao']) . '</div>', 'class' => 'goldprice-td goldprice-td-0');
  $row[] = array('data' => '<div class="item-relative">' . drupal_render($form['phi_sjc_9999_banra']) . '</div>', 'class' => 'goldprice-td goldprice-td-1');
  $rows[] = $row;

  //Nguyen lieu 99.9
  $row = array();
  $row[] = array('data' => t('<span class="title clear-block clear size-18 normal">Nguyên liệu 999.9</span><span class="sub-title clear size-13 normal">(nghìn/chỉ)</span>', array(), 'vi'), 'class' => 'first');
  $row[] = array('data' => '<div class="item-relative">' . drupal_render($form['nguyen_lieu_999_muavao']) . '</div>', 'class' => 'goldprice-td goldprice-td-0');
  $row[] = array('data' => '<div class="item-relative">' . drupal_render($form['nguyen_lieu_999_banra']) . '</div>', 'class' => 'goldprice-td goldprice-td-1');
  $rows[] = $row;

  //Phi SJC 99
  $row = array();
  $row[] = array('data' => t('<span class="title clear-block clear size-18 normal">Nguyên liệu 99.9</span><span class="sub-title clear size-13 normal">(nghìn/chỉ)</span>', array(), 'vi'), 'class' => 'first');
  $row[] = array('data' => '<div class="item-relative">' . drupal_render($form['nguyen_lieu_99_muavao']) . '</div>', 'class' => 'goldprice-td goldprice-td-0');
  $row[] = array('data' => '<div class="item-relative">' . drupal_render($form['nguyen_lieu_99_banra']) . '</div>', 'class' => 'goldprice-td goldprice-td-1');
  $rows[] = $row;

  $row = array();
  $row[] = array('data' => $trangthaigiaodich_link . drupal_render($form['submit1']), 'class' => 'form-footer-container', 'colspan' => 3);
  $rows[] = $row;

  $output .= theme('table', NULL, $rows, array('class' => 'goldprice-view ' . $trangthaigiaodich_class));
  $output .= drupal_render($form);
  return $output;
}

function doji_gold_trang_thai_giao_dich($op, $v) {
  if (is_numeric($op) && in_array($op, array(0, 1))) {
    variable_set('trangthaigiaodich', $op);
  }
  else if ($op == 'extra' && in_array($v, array(0, 1))) {
    variable_set('trangthaigiaodich_extra', $v);
  }
  $dojigold_prefix_filename = variable_get('dojigold_prefix_filename', -32767);
  $dojigold_prefix_filename += 1;
  variable_set('dojigold_prefix_filename', $dojigold_prefix_filename);

  drupal_goto('<front>');
}

function doji_gold_price_value_validate($gold_prices = array()) {
  $error = 0;
  $gmin = 1500;

  if ($gold_prices['hn_le_muavao'] < $gmin || $gold_prices['hn_le_banra'] < $gmin || $gold_prices['hn_buon_muavao'] < $gmin || $gold_prices['hn_buon_banra'] < $gmin || $gold_prices['hcm_le_muavao'] < $gmin || $gold_prices['hcm_le_banra'] < $gmin || $gold_prices['hcm_buon_muavao'] < $gmin || $gold_prices['hcm_buon_banra'] < $gmin || $gold_prices['phi_sjc_9999_muavao'] < $gmin || $gold_prices['phi_sjc_9999_banra'] < $gmin || $gold_prices['nguyen_lieu_999_muavao'] < $gmin || $gold_prices['nguyen_lieu_999_banra'] < $gmin || $gold_prices['nguyen_lieu_99_muavao'] < $gmin || $gold_prices['nguyen_lieu_99_banra'] < $gmin) {
    form_set_error('name', t('Giá nhập vào chưa chính xác. Xin vui lòng kiểm tra lại', array(), 'vi'));
    $error++;
  }
  if ($gold_prices['hn_le_muavao'] > $gold_prices['hn_le_banra']) {
    form_set_error('name', t('DOJI HN mua lẻ > DOJI HN bán lẻ', array(), 'vi'));
    $error++;
  }
  if ($gold_prices['hn_buon_muavao'] > $gold_prices['hn_buon_banra']) {
    form_set_error('name', t('DOJI HN mua buôn > DOJI HN bán buôn', array(), 'vi'));
    $error++;
  }
  if ($gold_prices['hn_buon_banra'] > $gold_prices['hn_le_banra']) {
    form_set_error('name', t('DOJI HN bán buôn > DOJI HN bán lẻ', array(), 'vi'));
    $error++;
  }

  //HCM
  if ($gold_prices['hcm_le_muavao'] > $gold_prices['hcm_le_banra']) {
    form_set_error('name', t('DOJI HCM mua lẻ > DOJI HCM bán lẻ', array(), 'vi'));
    $error++;
  }
  if ($gold_prices['hcm_buon_muavao'] > $gold_prices['hcm_buon_banra']) {
    form_set_error('name', t('DOJI HCM mua buôn > DOJI HCM bán buôn', array(), 'vi'));
    $error++;
  }
  if ($gold_prices['hcm_buon_banra'] > $gold_prices['hcm_le_banra']) {
    form_set_error('name', t('DOJI HCM bán buôn > DOJI HCM bán lẻ', array(), 'vi'));
    $error++;
  }

  //PHI SJC 99.99
  if ($gold_prices['phi_sjc_9999_muavao'] > $gold_prices['phi_sjc_9999_banra']) {
    form_set_error('name', t('Phi SJC 99.99 mua > Phi SJC 99.99 bán', array(), 'vi'));
    $error++;
  }

  //Nguyên liệu (999.9)
  if ($gold_prices['nguyen_lieu_999_muavao'] > $gold_prices['nguyen_lieu_999_banra']) {
    form_set_error('name', t('Nguyên liệu 999.9 mua > Nguyên liệu 999.9 bán', array(), 'vi'));
    $error++;
  }

  //Nguyên liệu (99.9)
  if ($gold_prices['nguyen_lieu_99_muavao'] > $gold_prices['nguyen_lieu_99_banra']) {
    form_set_error('name', t('Nguyên liệu 99.9 mua > Nguyên liệu 99.9 bán', array(), 'vi'));
    $error++;
  }

  return $error;
}

function doji_gold_price_footer() {
  if (isset($_SESSION['doji_gold_update']) && $_SESSION['doji_gold_update']) {
    _doji_gold_price_update();
    doji_led_put_to_mysqlserver();
  }
}

function _doji_gold_price_update() {
  if ($_SERVER['HTTP_HOST'] == 'giavang.doji.vn' && variable_get('trangthaigiaodich', 1)) {
    $node = doji_get_node('last', 'goldprice', 0);
   // doji_sms_push_to_api('insert', $node);
    doji_led_put_to_mysqlserver('insert', $node);
    if (function_exists('doji_api_giavang_trongnuoc')) {
      doji_api_giavang_trongnuoc('new');
      doji_api_giavang_quocte('new');
      doji_api_giavang_trangsucthamkhao('new');
	  db_query("DELETE FROM {cache_page};");
    }
  }
  doji_charts_create();
 
  unset($_SESSION['doji_gold_update']);
}