<?php
// $Id: doji_diadiem.module,v 1.0 2011/10/13 13:25:57 tvazone Exp $


/**
 * Implements hook_menu().
 */
function doji_cuahang_menu() {
  
  $items = array();
  $items['doji/admin/cuahang'] = array(
    'title' => t('Quản lý cua hang', array(), 'vi'),
    'page callback' => 'doji_cuahang_admin',
    'access arguments' => array('access administration pages'),
    'weight' => 10,
    'type' => MENU_LOCAL_TASK,
  );

  $items['system/doji/cuahang_1'] = array(
    'title' => t('Quản lý cua hang', array(), 'vi'),
    'page callback' => 'doji_api_cuahang_page',
    'access arguments' => array('access administration pages'),
    'weight' => 10,
    'type' => MENU_LOCAL_TASK,
  );


  return $items;
}


function doji_cuahang_admin() {
	module_load_include('inc', 'node', 'node.pages');
	$node = doji_get_node('first', 'cuahang');

	if (!isset($node->nid)) {
    	$node = doji_get_node_base(array('type' => 'cuahang'));
  	}
  	
  	$form = node_page_edit($node);
  	$form = '<div class="clear-form goldprice-sxht">' . $form . '</div>';
  	return $form;
}
function doji_api_cuahang_page($op) {
  global $user;
  if (!in_array($op, array('new'))) {
    unset($op);
  }

  drupal_set_header('Content-Type: text/xml');
  $output = doji_api_cuahang($op);
  $output .= "<Source>DOJI GOLD : http://giavang.doji.vn</Source>\n";
  $output = "<?xml version='1.0' encoding='utf-8'?>\n<GoldList>$output</GoldList>";
  echo $output;
}

function doji_api_cuahang($op) {
  global $user;
  $rows = array();

  $data_path_details = doji_get_data_path_details();
  $data_path_details['filepath'] = $data_path_details['path'] . '/'  . $data_path_details['prefix'] .  'api_cuahang.dat';
  $output = file_get_contents($data_path_details['filepath']);

  if (empty($output) || !$output || $op == 'new') {
    $node = doji_get_node('last');
    $node1 = doji_get_node('first', 'cuahang');
    $content_groups = fieldgroup_groups('goldprice');
    $datime = '    <DateTime>' . format_date($node->created, 'custom', 'd-m-Y') . '</DateTime>';

    foreach ($node1->field_dlieu_ch_1 as $k => $v) {

      $fieldname = str_replace('group_', 'field_', $node1->field_dlieu_ch_1[$k]['value']);
      $muavao = format_number(str_replace(',', '', $node->{$fieldname . '_muavao'}[0]['value']));
      $banra = format_number(str_replace(',', '', $node->{$fieldname . '_banra'}[0]['value']));

      if ($muavao <= 0) {
        $muavao = '-';
      }
      if ($banra <= 0) {
        $banra = '-';
      }

      if ($node1->field_label_ch_1[$k]['value'] && !empty($node1->field_label_ch_1[$k]['value'])) {
        $label = $node1->field_label_ch_1[$k]['value'];
      }
      else {
        $label = $content_groups[$node1->field_label_ch_1[$k]['value']]['label'];
        $label = preg_replace('|(.*?)\(.*|i', '$1', $label);
      }

      $key = $node1->field_key_ch_1[$k]['value'];
      $rows[] = "    <Row Name='$label' Key='$key' Sell='$banra' Buy='$muavao' />\n";

    }

    if (count($rows)) {
      $output = "<LED>\n$datime\n" . implode("", $rows) . "</LED>\n";
      file_save_data($output, $data_path_details['filepath'], FILE_EXISTS_REPLACE);
    }
  }

  return $output;
}




function  doji_cuahang_content_page_callback($term =1){
  if(arg(2) == 'callback'){
    $term = $_GET['tid'];
  }
  $query = db_query("
    SELECT a.field_diadiem_phone_value, b.field_diadiem_diachi_value, c.field_diadiem_ten_value,
    d.field_diadiem_lat_value, e.field_diadiem_long_value
    FROM content_field_diadiem_phone a,content_field_diadiem_diachi b,content_field_diadiem_ten c,
    content_field_diadiem_lat d, content_field_diadiem_long e
    WHERE a.delta = b.delta and b.delta = c.delta and c.delta and c.delta = d.delta and d.delta = e.delta
    and e.delta in
    (SELECT delta from content_field_diadiem_city where field_diadiem_city_value ='%d' )",$term
  );
  $address = array();
  while($result = db_fetch_array($query)) {
    array_push($address,$result);
  }
  drupal_set_title('');
  drupal_add_js(drupal_get_path('module', 'doji_cuahang') . '/js/doji_cuahang.js');
  $output = theme('cuahang', $address);
  if(arg(2) == 'callback') {
  drupal_json(array('status' => TRUE, 'data' => $output));
  exit();
  }
  else
    return $output;
}

function doji_cuahang_content_page() {
	drupal_set_title('');	
	drupal_add_js(drupal_get_path('module', 'cuahang') . '/js/doji_cuahang.js');
  	$content = doji_get_node('first', 'cuahang');
	$output = theme('cuahang', $content);
	return $output;
}

/**
 * Implementation of hook_nodeapi().
 *
 */
function doji_cuahang_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  if ($node->type == 'cuahang' && arg(1) != 'admin' && in_array($op, array('view', 'insert', 'update'))) {
    drupal_get_messages();
    drupal_set_message(t('Thêm hiển thị thành công', array(), 'vi'));
    drupal_goto('doji/admin/cuahang');
  }
}


/**
 * Implementation of hook_theme().
 */
function doji_cuahang_theme() {
  return array(
    'cuahang_node_form' => array(
      'arguments' => array(
        'form' => array()
      )
    ),
    'cuahang' => array(
    	'arguments' => array('content' => NULL),
    	'template' => 'cuahang',
    	'path' => drupal_get_path('module', 'doji_cuahang') . '/templates',
    	)
  );
}

function theme_cuahang_node_form($form) {
  drupal_set_title('');
  $output ='';
  $button = drupal_render($form['buttons']['submit']);
  $button = '<div class="m-b-10">' . $button . '</div>';
  $output .= drupal_render($form['group_field_cua_hang']).$button;

  $output .= drupal_render($form['group_field_cua_hang_2']).$button;

  $output .= '<div style="display:none">' . drupal_render($form) . '</div>';
  return $output;
}